### ISSUE TITLE
AttributeError: module 'types' has no attribute 'GenericAlias'

### ISSUE THREAD

**Issue by alamia442** [jurakin/kukajto-downloader#1]
Traceback (most recent call last):
  File "/usr/local/bin/kukajto-downloader", line 5, in <module>
    from kukajto_downloader.web import main
  File "/usr/local/lib/python3.8/dist-packages/kukajto_downloader/__init__.py", line 1, in <module>
    from .wrapper import Kukaj
  File "/usr/local/lib/python3.8/dist-packages/kukajto_downloader/wrapper.py", line 4, in <module>
    from .scraper import Scraper
  File "/usr/local/lib/python3.8/dist-packages/kukajto_downloader/scraper.py", line 3, in <module>
    from .utils import urlparse
  File "/usr/local/lib/python3.8/dist-packages/kukajto_downloader/utils.py", line 253, in <module>
    class _NetlocResultMixinBase(object):
  File "/usr/local/lib/python3.8/dist-packages/kukajto_downloader/utils.py", line 289, in _NetlocResultMixinBase
    __class_getitem__ = classmethod(types.GenericAlias)
AttributeError: module 'types' has no attribute 'GenericAlias'

Python 3.8.10

**Comment by jurakin** [comment]
I think the problem is that for some reason I downloaded `urllib.parse` for my version of python 3.10.6, which is incompatible with yours. I changed the code so it used the built-in module. I committed the changes to the [dev branch](https://github.com/jurakin/kukajto-downloader/tree/dev) and it should be fine. Let me know if it works.
