### ISSUE TITLE
There is no such driver by url

### ISSUE THREAD

**Issue by apanmarian** [jurakin/kukajto-downloader#5]
Starting the Kukajto Downloader produces this error:

C:\Windows\System32>"C:\Program Files (x86)\Kukajto Downloader\kukajto-downloader.exe"
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "src\kukajto_downloader\web\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "src\kukajto_downloader\web\__main__.py", line 27, in <module>
  File "src\kukajto_downloader\web\__main__.py", line 20, in create_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/127.0.6533/chromedriver_win32.zip
[6040] Failed to execute script 'main' due to unhandled exception!

**Comment by jurakin** [comment]
Yes, the current version of the exe is broken due to a change in the Chrome api that webdriver_manager doesn't expect. But you should still be able to use the pip version:
- `pip install kukajto-downloader`
- install webdriver manually (see https://pypi.org/project/selenium, section *Drivers*)
- `kukajto-downloader`
